<a href="https://colab.research.google.com/github/JsNcAr/Metodos1_JasonArias_AngieRicaurte/blob/ramaALRR/Ejercicio_12.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import numpy as np
import matplotlib.pyplot as plt
import sympy as sym

In [9]:
x=0.5
y=0.5
z=0.5
h=0.01


In [10]:
def f(x, y, z):
    return 6 * x - 2 * (np.cos(y * z)) - 1


def g(x, y, z):
    return 9 * y + np.sqrt((x**2) + (np.sin(z)) + (1)) + 0.9


def t(x, y, z):
    return 60 * z + 3 * (np.exp(-x * y)) + 10 * (np.pi) - 3

In [11]:
#a)
def central_derivative_x(f, x, y, z, h):
    return (f(x - 2 * h, y, z) - 8 * f(x - h, y, z) + 8 * f(x + h, y, z) -
            f(x + 2 * h, y, z)) / (12 * h)


def central_derivative_y(f, x, y, z, h):
    return (f(x, y - 2 * h, z) - 8 * f(x, y - h, z) + 8 * f(x, y + h, z) -
            f(x, y + 2 * h, z)) / (12 * h)


def central_derivative_z(f, x, y, z, h):
    return (f(x, y, z - 2 * h) - 8 * f(x, y, z - h) + 8 * f(x, y, z + h) -
            f(x, y, z + 2 * h)) / (12 * h)

In [12]:
def Jacobiano_4(f, g, t, x, y, z, h):
    matriz = np.zeros((3, 3))
    df_dx = central_derivative_x(f, x, y, z, h)
    df_dy = central_derivative_y(f, x, y, z, h)
    df_dz = central_derivative_z(f, x, y, z, h)

    dg_dx = central_derivative_x(g, x, y, z, h)
    dg_dy = central_derivative_y(g, x, y, z, h)
    dg_dz = central_derivative_z(g, x, y, z, h)

    dt_dx = central_derivative_x(t, x, y, z, h)
    dt_dy = central_derivative_y(t, x, y, z, h)
    dt_dz = central_derivative_z(t, x, y, z, h)

    matriz[0, 0] = df_dx
    matriz[0, 1] = df_dy
    matriz[0, 2] = df_dz

    matriz[1, 0] = dg_dx
    matriz[1, 1] = dg_dy
    matriz[1, 2] = dg_dz

    matriz[2, 0] = dt_dx
    matriz[2, 1] = dt_dy
    matriz[2, 2] = dt_dz

    return matriz

In [13]:
#b)
J = Jacobiano_4(f, g, t, x, y, z, h)
print(J)

[[ 6.          0.24740396  0.24740396]
 [ 0.38020609  9.          0.33366224]
 [-1.16820117 -1.16820117 60.        ]]


In [14]:
#c)

def CentralDerivative_x(f,x,y,z,h):
    d = (f((x+h),y,z) - f((x-h),y,z))/(2*h)      
    return d

def CentralDerivative_y(f,x,y,z,h):
    d = (f(x,(y+h),z) - f(x,(y-h),z))/(2*h)
    return d

def CentralDerivative_z(f,x,y,z,h):
    d = (f(x,y,(z+h)) - f(x,y,(z-h)))/(2*h)
    return d


In [15]:
def Jacobiano_2(f, g, t, x, y, z, h):

    matriz = np.zeros((3, 3))
    df_dx = CentralDerivative_x(f, x, y, z, h)
    df_dy = CentralDerivative_y(f, x, y, z, h)
    df_dz = CentralDerivative_z(f, x, y, z, h)

    dg_dx = CentralDerivative_x(g, x, y, z, h)
    dg_dy = CentralDerivative_y(g, x, y, z, h)
    dg_dz = CentralDerivative_z(g, x, y, z, h)

    dt_dx = CentralDerivative_x(t, x, y, z, h)
    dt_dy = CentralDerivative_y(t, x, y, z, h)
    dt_dz = CentralDerivative_z(t, x, y, z, h)

    matriz[0, 0] = df_dx
    matriz[0, 1] = df_dy
    matriz[0, 2] = df_dz

    matriz[1, 0] = dg_dx
    matriz[1, 1] = dg_dy
    matriz[1, 2] = dg_dz

    matriz[2, 0] = dt_dx
    matriz[2, 1] = dt_dy
    matriz[2, 2] = dt_dz

    return matriz


In [16]:
Resultado = Jacobiano_2(f, g, t, x, y, z, h)
print(Resultado)

[[ 6.          0.24740293  0.24740293]
 [ 0.38019669  9.          0.33366006]
 [-1.16820604 -1.16820604 60.        ]]


In [17]:
print(J)

[[ 6.          0.24740396  0.24740396]
 [ 0.38020609  9.          0.33366224]
 [-1.16820117 -1.16820117 60.        ]]


In [18]:
print(f"El error es de \n {np.abs(J-Resultado)}")

El error es de 
 [[0.00000000e+00 1.03084339e-06 1.03084339e-06]
 [9.40190904e-06 2.30926389e-14 2.17470794e-06]
 [4.86753517e-06 4.86753517e-06 2.41584530e-13]]
