<a href="https://colab.research.google.com/github/JsNcAr/Metodos1_JasonArias_AngieRicaurte/blob/ramaALRR/Ejercicio3_Algebralineal_Multiplicaciondematrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [5]:
A = np.array([[1, 0, 0],
              [5, 1, 0],
              [-2, 3, 1]])

B = np.array([[4, -2, 1],
              [0, 3, 7],
              [0, 0, 2]])

if A.shape[1] != B.shape[0]:
    print("Error: las dimensiones de las matrices no son compatibles para la multiplicación.")
else:
  C = np.zeros((A.shape[0], B.shape[1]))
  for i in range(A.shape[0]):
    for j in range(B.shape[1]):
      for k in range(A.shape[1]):
        C[i,j] += A[i,k] * B[k,j]
print("El resultado de la multiplicación AB es:")
print(C)

El resultado de la multiplicación AB es:
[[ 4. -2.  1.]
 [20. -7. 12.]
 [-8. 13. 21.]]
