# LU Decomposition

In [1]:
import numpy as np

In [2]:
def LU(A):
    n = len(A)
    L = np.eye(n)
    U = np.zeros((n,n))
    for k in range(n):
        U[k,k] = A[k,k] - np.dot(L[k,:k], U[:k,k])
        for i in range(k+1, n):
            L[i,k] = (A[i,k] - np.dot(L[i,:k], U[:k,k]))/U[k,k]
        for j in range(k+1, n):
            U[k,j] = A[k,j] - np.dot(L[k,:k], U[:k,j])
    return L, U

In [3]:
A = np.array([[4, -2, 1], [20, -7, 12], [-8, 13, 17]])

L, U = LU(A)

print("L: \n", L)
print("U: \n", U)

L: 
 [[ 1.  0.  0.]
 [ 5.  1.  0.]
 [-2.  3.  1.]]
U: 
 [[ 4. -2.  1.]
 [ 0.  3.  7.]
 [ 0.  0. -2.]]
