## Librerias

In [ ]:
import numpy as np

## Problema 1

Considere $D = \{d_1, \cdots d_n\}$ un conjunto de documentos y $T = \{t_1, \cdots t_m\}$ un conjunto de términos (palabras). Considere además, $TD = (TD_{i,j})_{i=1\cdots m, j = 1 \cdots n}$ como una matriz tal que $TD_{i, j}$ indica el número de veces que el término $t_i$ (palabra) aparece en el documento $d_j$ (Los documentos están el las columnas, las palabras en las filas). También, considere $l_i$ como la longitud (número de letras) del término $t_i$, y sea $L = (l_1, \cdots, l_m)$ un vector columna. Adicionalmente, asuma un proceso en el cual el documento $d_j$ is escogido aleatoriamente con probabilidad uniforme y el termino $t_i$, presente en el documento $d_j$,  es escogido con una probabilidad proporcional a la frecuencia de $t_i$ en el documento $d_j$.

Para las siguientes expresiones usted debe mostrar lo siguiente:

*   La expresión matemática de lo que se le pide en términos de $TD$, $L$, constantes (es decir en terminos de matrices, vectores, escalares) y operaciones algebraícas o del algebra lineal.
*   Una expresión en `numpy`, tal que al ser evaluada se obtenga, la matriz, el vector o el escalar requerido (La expresión debe estar descrita en términos del algebra lineal, es decir no se pueden usar estructuras de control, `for`, `while`, etc)
*   El resultado de las expresiones usando los siguientes datos:


$$
TD =  \begin{bmatrix}
2 & 3 & 0 & 3 & 7 \\  0 & 5 & 5 & 0 & 3 \\ 5 & 0 & 7 & 3 & 3 \\ 3 & 1 & 0 & 9 & 9 \\ 0 & 0 & 7 & 1 & 3 \\ 6 & 9 & 4 & 6 & 0 
\end{bmatrix}, \quad L = \begin{bmatrix}
5 \\  2 \\ 3 \\ 6 \\ 4 \\ 3 \\ 
\end{bmatrix}
$$





In [ ]:
# Arrays for the computations

TD = np.array([[2, 3, 0, 3, 7],[0, 5, 5, 0, 3],[5, 0, 7, 3, 3],[3, 1, 0, 9, 9],[0, 0, 7, 1, 3],[6, 9, 4, 6, 0]])
L = np.array([[5, 2, 3, 6, 4, 3]]).T
m , n = TD.shape

TD, L

(array([[2, 3, 0, 3, 7],
        [0, 5, 5, 0, 3],
        [5, 0, 7, 3, 3],
        [3, 1, 0, 9, 9],
        [0, 0, 7, 1, 3],
        [6, 9, 4, 6, 0]]),
 array([[5],
        [2],
        [3],
        [6],
        [4],
        [3]]))

(a) Matriz $P(T, D)$ (cada posición de la matriz, $P(T, D)_{i,j}$ indica la probabilidad conjunta del término $t_i$ y el documento $d_j$, $P(t_j, d_j)$)

Escriba su expresión matemática a continuación, 

$$
P(T, D)_{i,j} = 
$$

In [ ]:
### Escriba e imprima la matriz con los valores de ejemplo a continuación
M1 = np.zeros((6, 5))
# su codigo aqui


# codigo para verificar su respuesta no modificar
print(M1.sum())
print(M1)

0.0
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


(b) Matriz $P(T|D)$

Escriba su expresión matemática a continuación, 

$$
P(T|D)_{i, j} =
$$

In [ ]:
### Escriba e imprima la matriz con los valores de ejemplo a continuación
M2 = np.zeros((6, 5))
# su codigo aqui


# codigo para verificar su respuesta no modificar
print(M2)
print(M2.sum(axis = 0))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[0. 0. 0. 0. 0.]


(c) Vector P(D)

Escriba su expresión matemática a continuación, 

$$
P(D)_j =
$$

In [ ]:
### Escriba e imprima el vector con los valores de ejemplo a continuación
P_D = np.zeros(5)
# su codigo aqui


# codigo para verificar su respuesta no modificar
print(P_D)

[0. 0. 0. 0. 0.]


## Problema 2
Continuación problema anterior

(d) Vector P(T)

Escriba su expresión matemática a continuación, 

$$
P(T)_i = 
$$

In [ ]:
### Escriba e imprima el vector con los valores de ejemplo a continuación
P_T = np.zeros(5)
# su codigo aqui


# codigo para verificar su respuesta no modificar
print(P_T.sum())
print(P_T)

0.0
[0. 0. 0. 0. 0.]


(e) Matriz $P(D|T)$

Escriba su expresión matemática a continuación, 

$$
P(D|T)_{i, j} = 
$$

In [ ]:
### Escriba e imprima la matriz con los valores de ejemplo a continuación
M3 = np.zeros((6, 5))
# su codigo aqui


# codigo para verificar su respuesta no modificar
print(M3.sum(axis=1).reshape((m,1)))
print(M3)

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


(f) Escalar $E[l]$ (el valor esperado de la variable aleatoria $l$ que corresponde a la longitud de un término escogido aleatoriamente) (sin importar el documento)

Escriba su expresión matemática a continuación, 

$$
E[l] = 
$$

In [ ]:
### Escriba e imprima el escalar con los valores de ejemplo a continuación
E_l = np.zeros(1)
# su codigo aqui


# codigo para verificar su respuesta no modificar
print(E_l)

[0.]
