## Librerias

In [2]:
import numpy as np

## Problema 2

Considere una cadena larga de resistencias como se muestra en la figura:

![](https://raw.githubusercontent.com/diegour1/CompMetodosComputacionales/main/DataFiles/image8.png)

Todos los resitores tienen las misma resistencia $R$. El voltage en la parte superior izquierda del sistema es $V_+ = 5 \text{V}$. El problema consiste en obtener los voltajes $V_1, \ldots, V_N$ de los puntos internos del circuito. 



a) Usando la ley de Ohm y la ley de corrientes de Kirchoff, la cual dice que la corriente total que fluye hacia afuera o hacia adentro de cada nodo del circuito es cero. Explique porqué los voltajes $V_1, \ldots, V_N$ cumplen con las siguientes ecuaciones.

$$3V_1 − V_2 − V_3 = V_+$$
$$− V_1 + 4V_2 − V_3 − V_4 = V_+,$$
$$\vdots$$
$$− V_{i − 2} − V_{i − 1} + 4V_i − V_{i + 1} − V_{i + 2} = 0,$$
$$\vdots$$
$$− V_{N − 3} − V_{N − 2}+ 4V_{N − 1} − V_N = 0,$$
$$− V_{N − 2} − V_{N − 1} + 3V_N = 0.$$

Pista: Para resolver esta pregunta se usa la ley de Ohm y la ley de corrientes de Kirchhoff. La cual dice que la corriente que fluye hacia adentro o hacia afuera de cada unión del circuito es cero. Por ejemplo para el voltaje $V_1$ se tiene que, 

$$
\frac{V_1-V_2}{R} + \frac{V_1-V_3}{R} + 
\frac{V_1-V_+}{R} = 0, 
$$

Tu explicación aquí

.

.

.

.

.


b) Escriba las ecuaciones de la forma $A\vec{x} = \vec{b}$ encuentre los valores de la matriz $A$ y del vector $\vec{b}$, para $N=6$. Imprima estos dos resultados en el notebook.



In [3]:
A = np.zeros((6, 6))
b = np.zeros(6)

# Tu codigo aqui


# Codigo para la verificacion (no modificar)
print(A)
print(b)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[0. 0. 0. 0. 0. 0.]


c) Escriba un programa que resuelva los valores de $V_i$ cuando $N=6$ es decir 6 nodos internos. Guarde e imprima los valores en el vector $\vec{x}$.



In [4]:
x = np.zeros(6)

# tu codigo aqui

# Codigo para la verificacion (no modificar)
print(x)

[0. 0. 0. 0. 0. 0.]


d) Encuentre la resistencia total $R_{(N=6)} = \alpha R$, para la red $N=6$, donde $\alpha$ es una constante, imprima el valor de $\alpha$.

In [5]:
alpha = 0

# Tu codigo aqui

# Codigo para la verificacion (no modificar)
print(alpha)

0


e) Explique qué haría usted para resolver la resistencia equivalente del circuito para un número infinito de nodos. 

.

.

.

.

.