In [1]:
import numpy as np

In [2]:
A = np.array([[1, 2, -1], [1, 0, 1], [4, -4, 5]])

In [3]:
np.linalg.eig(A)

(array([3., 2., 1.]),
 array([[-0.23570226,  0.43643578,  0.40824829],
        [ 0.23570226, -0.21821789, -0.40824829],
        [ 0.94280904, -0.87287156, -0.81649658]]))

In [4]:
def EigValue(A, c=0, itmax=1000, tol=1e-14):
    n = A.shape[0]
    
    v0 = np.zeros(n)

    v0[c] = 1.

    lambda1 = 0.

    for k in range(itmax):
        v1 = A.dot(v0)
        v1 = v1/np.linalg.norm(v1)

        v2 = A.dot(v1)
        v2 = v2/np.linalg.norm(v1)

        lambda0 = lambda1
        lambda1 = v2[0]/v1[0]
        
        v0 = v2

        if np.abs(lambda1 - lambda0) <= tol:
            break
    return lambda1, v1


In [5]:
value1, vector1 = EigValue(A, c=0)
print(value1, vector1)

3.0000000000000058 [-0.23570226  0.23570226  0.94280904]


In [6]:
def Tensor(v):
    n = v.shape[0]
    T = np.zeros((n, n))
    for i in range(n):
        for j in range(n):
            T[i, j] = v[i]*v[j]
    return T

In [8]:
B = A -

[[1. 0.]
 [0. 0.]]
